# Generated by Django 4.1.6 on 2023-03-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranqiapp', '0003_remove_userinfo_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='zhuanxianggz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('yujijianshao', models.FloatField()),
                ('zhanbi', models.FloatField()),
            ],
        ),
    ]
