# Generated by Django 4.1.6 on 2023-03-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranqiapp', '0004_zhuanxianggz'),
    ]

    operations = [
        migrations.CreateModel(
            name='changes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyin', models.FloatField()),
                ('sellout', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='gouxiaochaarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leakloss', models.FloatField()),
                ('pipechanges', models.FloatField()),
                ('abnormalcal', models.FloatField()),
                ('overageloss', models.FloatField()),
                ('temperature', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='yongqiyuce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('series', models.IntegerField()),
            ],
        ),
    ]
