# Generated by Django 4.1.6 on 2023-03-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranqiapp', '0005_changes_gouxiaochaarea_yongqiyuce'),
    ]

    operations = [
        migrations.CreateModel(
            name='biaoju',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('jiangdiliang', models.FloatField()),
                ('sunshiqi', models.FloatField()),
                ('chaoling', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='dishang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('undernum', models.IntegerField()),
                ('cunliang', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='jiance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lossper', models.FloatField()),
                ('bushou', models.FloatField()),
                ('jiangdi', models.FloatField()),
                ('sunshi', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
