# Generated by Django 4.1.6 on 2023-03-20 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ranqiapp', '0006_biaoju_dishang_jiance_alter_userinfo_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='guanwang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guanwangname', models.CharField(max_length=64)),
                ('guandaolen', models.FloatField()),
                ('guige', models.CharField(max_length=32)),
                ('textile', models.CharField(max_length=32)),
                ('weihu', models.CharField(max_length=64)),
                ('jilu', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellername', models.CharField(max_length=64)),
                ('client', models.CharField(max_length=32)),
                ('contractnum', models.CharField(max_length=32)),
                ('contracttype', models.CharField(max_length=32)),
                ('start', models.CharField(max_length=32)),
                ('end', models.CharField(max_length=32)),
                ('product', models.CharField(max_length=32)),
                ('order', models.IntegerField()),
                ('money', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='qiyuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qiyuanname', models.CharField(max_length=64)),
                ('qiyuantype', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=64)),
                ('sum', models.FloatField()),
                ('available', models.FloatField()),
                ('arranged', models.FloatField()),
                ('alarm', models.FloatField()),
                ('use', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='zidian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zidianname', models.CharField(max_length=64)),
                ('xiangname', models.CharField(max_length=32)),
                ('value', models.FloatField()),
                ('discription', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phonenum',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='realname',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='youxiang',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
