# Generated by Django 4.1.6 on 2023-03-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranqiapp', '0007_guanwang_other_qiyuan_zidian_userinfo_phonenum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='phonenum',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='realname',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='youxiang',
        ),
    ]
