# Generated by Django 4.1.6 on 2023-04-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranqiapp', '0008_remove_userinfo_phonenum_remove_userinfo_realname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qp2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qpdate', models.DateField()),
                ('zhibiao', models.IntegerField()),
                ('typeqp', models.IntegerField()),
                ('buyin', models.IntegerField()),
                ('pipebuy', models.FloatField()),
                ('CNG', models.FloatField()),
                ('LNG', models.FloatField()),
            ],
        ),
    ]
