# Generated by Django 3.2.8 on 2023-04-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranqiapp', '0010_dailycng_dailylng_dailypipe_fangsan1_fangsan2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyin1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyin1_date', models.DateField()),
                ('buyin1_buyin', models.FloatField()),
                ('buyin1_unit', models.CharField(max_length=32)),
                ('buyin1_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='buyin2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyin2_date', models.DateField()),
                ('buyin2_buyin', models.FloatField()),
                ('buyin2_unit', models.CharField(max_length=32)),
                ('buyin2_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='buyin3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyin3_date', models.DateField()),
                ('buyin3_buyin', models.FloatField()),
                ('buyin3_unit', models.CharField(max_length=32)),
                ('buyin3_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='compensate1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compensate1_date', models.DateField()),
                ('compensate1_num', models.IntegerField()),
                ('compensate1_area', models.CharField(max_length=64)),
                ('compensate1_type', models.CharField(max_length=64)),
                ('compensate1_loss', models.FloatField()),
                ('compensate1_money', models.FloatField()),
                ('compensate1_make', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='compensate2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compensate2_date', models.DateField()),
                ('compensate2_num', models.IntegerField()),
                ('compensate2_area', models.CharField(max_length=64)),
                ('compensate2_type', models.CharField(max_length=64)),
                ('compensate2_loss', models.FloatField()),
                ('compensate2_money', models.FloatField()),
                ('compensate2_make', models.CharField(max_length=64)),
            ],
        ),
    ]
