# Generated by Django 3.2.8 on 2023-05-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranqiapp', '0011_buyin1_buyin2_buyin3_compensate1_compensate2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensateForce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='索赔日期')),
                ('type', models.SmallIntegerField(choices=[(1, '非法用气索赔'), (2, '外力损坏索赔')], default=1, verbose_name='索赔类型')),
                ('reason', models.CharField(max_length=128, verbose_name='索赔原因')),
                ('amount', models.IntegerField(verbose_name='索赔气量')),
                ('area', models.SmallIntegerField(choices=[(1, '第一营业所'), (2, '第二营业所'), (3, '第三营业所'), (4, '浦江营业所')], default=1, verbose_name='索赔区域')),
                ('state', models.SmallIntegerField(choices=[(1, '待赔偿'), (2, '已赔偿')], default=1, verbose_name='状态')),
            ],
        ),
        migrations.DeleteModel(
            name='compensate2',
        ),
    ]
