# Generated by Django 3.2.8 on 2023-05-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranqiapp', '0012_auto_20230502_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '普通用户'), (2, '管理员')], default=1, verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='compensateforce',
            name='state',
            field=models.SmallIntegerField(choices=[(1, '待赔偿'), (2, '已赔偿')], default=1, verbose_name='索赔状态'),
        ),
    ]
