# Generated by Django 3.2.8 on 2023-05-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranqiapp', '0015_alter_userinfo_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='购买日期')),
                ('type', models.SmallIntegerField(choices=[(1, 'CNG'), (2, 'LNG'), (3, '管输')], default=1, verbose_name='购气类型')),
                ('unit', models.CharField(max_length=128, verbose_name='购气单位')),
                ('price', models.CharField(max_length=128, verbose_name='购气价格')),
            ],
        ),
        migrations.RenameModel(
            old_name='CompensateForce',
            new_name='Compensate',
        ),
    ]
