# Generated by Django 3.2.8 on 2023-05-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranqiapp', '0017_buy_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='储存日期')),
                ('type', models.SmallIntegerField(choices=[(1, 'CNG'), (2, 'LNG'), (3, '管输')], default=1, verbose_name='购气类型')),
                ('tank', models.IntegerField(verbose_name='油罐ID')),
                ('height', models.IntegerField(verbose_name='液位高度')),
                ('area', models.IntegerField(verbose_name='截面面积')),
                ('density', models.IntegerField(verbose_name='液体密度')),
                ('factor', models.IntegerField(verbose_name='压缩因子')),
                ('temperature', models.IntegerField(verbose_name='热力学温度')),
                ('pressu', models.IntegerField(verbose_name='压强')),
            ],
        ),
    ]
