# Generated by Django 3.2.8 on 2023-05-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranqiapp', '0019_rename_pressu_store_pressure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='销售日期')),
                ('type', models.SmallIntegerField(choices=[(1, '居民户'), (2, '工业户'), (3, '商业户')], default=1, verbose_name='用户类型')),
                ('amount', models.IntegerField(verbose_name='销售气量')),
                ('price', models.CharField(max_length=128, verbose_name='销售气价')),
                ('area', models.SmallIntegerField(choices=[(1, '第一营业所'), (2, '第二营业所'), (3, '第三营业所'), (4, '浦江营业所')], default=1, verbose_name='销售区域')),
            ],
        ),
    ]
