# Generated by Django 3.2.8 on 2023-05-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranqiapp', '0020_sell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diffuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='放散日期')),
                ('type', models.SmallIntegerField(choices=[(1, '天然气'), (2, '液化气')], default=1, verbose_name='气体类型')),
                ('reason', models.CharField(max_length=128, verbose_name='放散')),
                ('amount', models.IntegerField(verbose_name='放散气量')),
                ('area', models.SmallIntegerField(choices=[(1, '第一营业所'), (2, '第二营业所'), (3, '第三营业所'), (4, '浦江营业所')], default=1, verbose_name='放散区域')),
            ],
        ),
        migrations.CreateModel(
            name='Use',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='自用日期')),
                ('amount', models.IntegerField(verbose_name='自用气量')),
                ('number', models.IntegerField(verbose_name='设备编号')),
                ('price', models.CharField(max_length=128, verbose_name='单位成本')),
                ('use', models.CharField(max_length=128, verbose_name='使用用途')),
            ],
        ),
    ]
