# Generated by Django 3.2.8 on 2023-05-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranqiapp', '0021_diffuse_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diffuse',
            name='reason',
            field=models.SmallIntegerField(choices=[(1, '维护'), (2, '泄露')], default=1, verbose_name='放散'),
        ),
        migrations.AlterField(
            model_name='use',
            name='use',
            field=models.IntegerField(choices=[(1, '生产加工'), (2, '供暖'), (3, '烹饪')], verbose_name='使用用途'),
        ),
    ]
